TeamPoki/Poki-iOS

- Poki-iOS/Poki-iOS.xcodeproj/project.pbxproj
- Poki-iOS/Poki-iOS/Controllers/AddPhotoViewController.swift
- Poki-iOS/Poki-iOS/Controllers/MainPageViewController.swift
- Poki-iOS/Poki-iOS/Views/AddPhtoPage/AddPhotoView.swift
#3[Feat] : UI및 오토레이아웃 구현
오류로 다시 PR 보냅니다
> #3[Feat] : UI및 오토레이아웃 구현

- Poki-iOS/Poki-iOS/Controllers/AddPhotoViewController.swift
- Poki-iOS/Poki-iOS/Info.plist
#9 [Feat] : plist 설정(privacy - Photo) + 제스처 이미지 피커뷰 구현완료
> #9 [Feat] : plist 설정(privacy - Photo) + 제스처 이미지 피커뷰 구현완료

- Poki-iOS/Poki-iOS/Controllers/AddPhotoViewController.swift
- Poki-iOS/Poki-iOS/Views/AddPhtoPage/AddPhotoView.swift
#33 [Design] : addPhtoView tagButton UI 변경 완료
> #33 [Design] : addPhtoView tagButton UI 변경 완료

- Poki-iOS/Poki-iOS/Controllers/AddPhotoViewController.swift
- Poki-iOS/Poki-iOS/Controllers/MainPageViewController.swift
#35 [Feat] : addPhtoView image 크기 제한 코드 구현 완료
> #35 [Feat] : addPhtoView image 크기 제한 코드 구현 완료

- Poki-iOS/Poki-iOS/Controllers/AddPhotoViewController.swift
- Poki-iOS/Poki-iOS/Views/AddPhtoPage/AddPhotoView.swift
- Poki-iOS/Poki-iOS/Views/TagViewPage/TagCollectionViewCell.swift
#37 [Feat] : addPhotoView keyboard view 관련 코드 구현 완료
> #37 [Feat] : addPhotoView keyboard view 관련 코드 구현 완료

- Poki-iOS/Poki-iOS/Views/AddPhtoPage/AddPhotoView.swift
#43[Design] addPhotoView UIImage backgroundView 설정 (develop 머지 후 리 푸쉬)
> #[Design] addPhotoView UIImage backgroundView 설정 (develop 머지 후 리 푸쉬)

- Poki-iOS/Poki-iOS/Controllers/SettingVC/SettingsViewController.swift
> [Feat]: 설정 페이지 UI구현

- Poki-iOS/Poki-iOS/Controllers/AddPhotoViewController.swift
#59 [Design] : addPhotoView ImageBackgroound 위치 조정
> #59 [Design] : addPhotoView ImageBackgroound 위치 조정

- Poki-iOS/Poki-iOS/Controllers/AddPhotoViewController.swift
- Poki-iOS/Poki-iOS/Models/Photo.swift
- Poki-iOS/Poki-iOS/Models/Tag.swift
- Poki-iOS/Poki-iOS/Network/NetworkingManager.swift
- Poki-iOS/Poki-iOS/Views/AddPhtoPage/AddPhotoView.swift
[FEATURE] addPhotoViewController에서 Creat, update 구현
> [FEATURE] addPhotoViewController에서 Creat, update 구현

- Poki-iOS/Poki-iOS/Controllers/SettingVC/NoticeListViewController.swift
> [Feat]: 공지사항 UI 구현

- Poki-iOS/Poki-iOS/Controllers/MyPageVC/MyPageViewController.swift
- Poki-iOS/Poki-iOS/Controllers/SettingVC/NoticeListViewController.swift
- Poki-iOS/Poki-iOS/Models/Notice.swift
- Poki-iOS/Poki-iOS/Views/SettingPage/NoticeListTableViewCell.swift
> #75 [Refactor]: NoticeListViewController 코드 분리 작업

- Poki-iOS/Poki-iOS/Controllers/SettingVC/NoticeListViewController.swift
- Poki-iOS/Poki-iOS/Controllers/SettingVC/SettingsViewController.swift
[Refactor]: SettingsViewController, NoticeListViewController 폰트 변경
> [Refactor]: SettingsViewController, NoticeListViewController 폰트 변경

- Poki-iOS/Poki-iOS/Controllers/SettingVC/SettingsViewController.swift
#88 [Feat]: 서비스 이용약관, 개인정보처리방침 화면연결
> #88 [Feat]: 서비스 이용약관, 개인정보처리방침 화면연결

- Poki-iOS/Poki-iOS/Controllers/MyPageVC/LikedPoseViewController.swift
> [Feat]: 찜한포즈 UI 구현

- Poki-iOS/Poki-iOS/Models/User.swift
- Poki-iOS/Poki-iOS/Network/FirestoreManager.swift
[Fix] : user와 firestore 데이터 연결 오류 수정
> [Fix] : user와 firestore 데이터 연결 오류 수정

- Poki-iOS/Poki-iOS/Controllers/MainPage/MainPageViewController.swift
- Poki-iOS/Poki-iOS/Helpers/SceneDelegate.swift
> #127 [Fix] : 로그인 페이지 전환 오류 수정

- Poki-iOS/Poki-iOS/Controllers/LoginViewController.swift
#129 [Feat] : 재 로그인 시 메인 페이지 고정 구현
> #129 [Feat] : 재 로그인 시 메인 페이지 고정 구현

- Poki-iOS/Poki-iOS.xcodeproj/project.pbxproj
- Poki-iOS/Poki-iOS/Controllers/MyPageVC/LikedPoseImageDetailViewController.swift
#117 LikedPoseImageDetailViewController 구현
> #117 [Feat]: LikedPoseImageDetailViewController 구현

- Poki-iOS/Poki-iOS/Controllers/SettingVC/AccountDeletionViewController.swift
- Poki-iOS/Poki-iOS/Network/AuthManager.swift
#132 [Feat] : auth 회원탈퇴 기능 구현 완료
> #132 [Feat] : auth 회원탈퇴 기능 구현 완료

- Poki-iOS/Poki-iOS.xcodeproj/project.pbxproj
- Poki-iOS/Poki-iOS/Controllers/MyPageVC/LikedPoseViewController.swift
- Poki-iOS/Poki-iOS/Controllers/MyPageVC/MyPageViewController.swift
- Poki-iOS/Poki-iOS/Controllers/RandomPoseViewController.swift
- Poki-iOS/Poki-iOS/Controllers/SettingVC/AccountDeletionViewController.swift
- Poki-iOS/Poki-iOS/Controllers/SignUpViewController.swift
- Poki-iOS/Poki-iOS/Models/User.swift
- Poki-iOS/Poki-iOS/Network/AuthManager.swift
- Poki-iOS/Poki-iOS/Network/UserDataManager.swift
#150 [Feat] : User 모델 생성 후 저장구현 완료
> #150 [Feat] : User 모델 생성 후 저장구현 완료

- Poki-iOS/Poki-iOS/Sources/Manager/AuthManager.swift
- Poki-iOS/Poki-iOS/Sources/Manager/FirestoreManager.swift
- Poki-iOS/Poki-iOS/Sources/Manager/PoseImageManager.swift
- Poki-iOS/Poki-iOS/Sources/Manager/StorageManager.swift
- Poki-iOS/Poki-iOS/Sources/Manager/UserDataManager.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Login/SignUp/SignUpVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/MainPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/MyPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/PoseSuggestion/RandomPose/RandomPoseVC.swift
#154 [Refactor] : UserDataManager 코드 리팩토링
> #154 [Refactor] : UserDataManager 코드 리팩토링

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/ProfileEdit/ProfileEditVC.swift
> #165 [Feat]: 프로필 수정 페이지UI 구현

- Poki-iOS/Poki-iOS/Sources/Manager/FirestoreManager.swift
- Poki-iOS/Poki-iOS/Sources/Manager/PoseImageManager.swift
- Poki-iOS/Poki-iOS/Sources/Manager/StorageManager.swift
- Poki-iOS/Poki-iOS/Sources/Manager/UserDataManager.swift
- Poki-iOS/Poki-iOS/Sources/Models/User.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Login/SignUp/SignUpVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/AddPhotoVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/AddPhotoView.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/MainPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/PhotoDetail/PhotoDetailVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/MyPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/Setting/AccountDeletionVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/PoseSuggestion/RandomPose/RandomPoseVC.swift
#203[FEATURE] : UserModel, PoseModel/ Firebase CRUD 구현
> #203[FEATURE] : UserModel, PoseModel/ Firebase CRUD 구현

- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/AddPhotoView.swift
#220 [MAINTENANCE] [Fix] : 추가하기페이지 날짜 자동 입력 설정
> #220 [Fix] : 추가하기페이지 날짜 자동 입력 설정

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/EmptyLikedPoseView.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
#217 [Feat]: 찜한사진 없을때 포즈 추천 화면 전환 구현
> #217 [Feat]: 찜한사진 없을때 포즈 추천 화면 전환 구현

- Poki-iOS/Poki-iOS/Sources/Manager/FirestoreManager.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/MyPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/PoseSuggestion/PoseSuggestionVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/PoseSuggestion/RandomPose/RandomPoseVC.swift
[MAINTENANCE][Fix] : 포즈추천페이지 데이터 로드시점 변경, 북마크 에러 수정
> [MAINTENANCE][Fix] : 포즈추천페이지 데이터 로드시점 변경, 북마크 에러 수정

- Poki-iOS/Poki-iOS/Sources/Presenter/Main/PhotoDetail/PhotoDetailVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseImageDetailVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/MyPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/ProfileEdit/ProfileEditVC.swift
#227 [FEATURE] mypage의 poseDetailPage 에서 북마크 해제 버튼 추가 구현
> #227 [FEATURE] mypage의 poseDetailPage 에서 북마크 해제 버튼 추가 구현

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/EmptyLikedPoseView.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/MyPageVC.swift
> [Refactor]: 코드 리팩토링

- Poki-iOS/Poki-iOS/Sources/Manager/StorageManager.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/AddPhotoVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/AddPhotoView.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/Tag/TagCell.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/Tag/TagVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Main/MainPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/ProfileEdit/ProfileEditVC.swift
> 코드 리펙토링 성공

- Poki-iOS/Poki-iOS/Sources/Presenter/Main/PhotoDetail/PhotoDetailVC.swift
> #251[Fix] 공유하기 버튼 이미지 저장 구현

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/MyPageVC.swift
[Refactor]: MyPageVC 오토레이아웃 수정
> [Refactor]: MyPageVC 오토레이아웃 수정

- Poki-iOS/Poki-iOS/Sources/Presenter/Login/LoginVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/Login/SignUp/SignUpView.swift
1. 로그인 페이지 유효성 검사 삭제
2. 로그인, 회원가입 버튼 하이라이트 색상 추가(버튼이 눌렸다는 것을 보여주기 위해)
3. 회원가입 페이지 - 가입하기 버튼 하이라이트 색상 추가 (2번과 이유 동일)
> #293 [Fix]: 로그인 페이지 및 회원가입 페이지 수정

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/MyPageVC.swift
#292 MyPageVC에 네컷추가 버튼 눌렀을때 메인페이지 이동
> #292 MyPageVC에 네컷추가 버튼 눌렀을때 메인페이지 이동

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/ProfileEdit/ProfileEditVC.swift
#302 [Refactor]: 프로필 수정페이지 닉네임 유효성 Alert 추가 및 hintLabel 변경
> #302 [Refactor]: 프로필 수정페이지 닉네임 유효성 Alert 추가 및 hintLabel 변경

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
1. 상단에 바 를 눌렀을 때, 애니메이션 동작하도록 코드 수정
> #258 [Fix]: 찜한 포즈 페이지 전환 시 화면 전환 부자연스러움

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/ProfileEdit/ProfileEditVC.swift
#311 [Refactor]: 프로필수정 페이지 키보드 엔터시 사라지게하기 및 유효성검사 변경
> #311 [Refactor]: 프로필수정 페이지 키보드 엔터시 사라지게하기 및 유효성검사 변경

- Poki-iOS/Poki-iOS/Sources/Presenter/Main/AddPhoto/AddPhotoVC.swift
#324 addphotiView tag image 이중 해결
> #324 addphotiView tag image 이중 해결

- Poki-iOS/Poki-iOS/Sources/Presenter/MyPage/LikedPose/LikedPoseVC.swift
#322 [Refactor]: LikedPoseVC 내 컬렉션뷰 화면이동 수정
> #322 [Refactor]: LikedPoseVC 내 컬렉션뷰 화면이동 수정

- Poki-iOS/Poki-iOS/Sources/Presenter/Main/PhotoDetail/PhotoDetailVC.swift
#328 [Feat]: PhotoDetailVC mainImageView 핀치 제스처 + 이미지 이동 구현
> #328 [Feat]: PhotoDetailVC mainImageView 핀치 제스처 + 이미지 이동 구현

- Poki-iOS/Poki-iOS/Sources/Presenter/Main/MainPageVC.swift
- Poki-iOS/Poki-iOS/Sources/Presenter/PoseSuggestion/RandomPose/RandomPoseVC.swift
1. MainPageVC - cellForItemAt 메서드 내부에 추가 234번째 줄
2. RandomPoseVC - setupPoseData 메서드 내부에 추가 146번째 줄
- setupPoseData 의 completion 파라미터 옵셔널 타입으로 수정
> #330 [Fix]: UIImageView 의 이미지가 설정되지 않았을 때, 인디케이터뷰 보여주기
